# Build stage
FROM golang:1.26-alpine AS builder

WORKDIR /api

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /readfriendlyapi ./cmd/api

# Run stage
FROM alpine:3.23.4

COPY --from=builder /readfriendlyapi /readfriendlyapi

CMD ["/readfriendlyapi"]
