# Build stage
FROM golang:1.26-alpine AS builder

WORKDIR /worker

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /readfriendlyworker ./cmd/worker

# Run stage
FROM alpine:3.23.4

COPY --from=builder /readfriendlyworker /readfriendlyworker

CMD ["/readfriendlyworker"]
