// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clippings": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Queues a webpage to be clipped and delivered to an email address in a specified format",
                "parameters": [
                    {
                        "description": "Clipping request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.postClippingRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.postClippingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clippings/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Checks the status of a clipping job (and provides a download URL when ready)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clipping ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.getClippingResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.getClippingResponse": {
            "type": "object",
            "properties": {
                "download_url": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ClippingStatus"
                }
            }
        },
        "main.postClippingRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "optional",
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/models.ClippingFormat"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "main.postClippingResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ClippingStatus"
                }
            }
        },
        "models.ClippingFormat": {
            "type": "string",
            "enum": [
                "pdf",
                "epub",
                "html"
            ],
            "x-enum-varnames": [
                "FormatPDF",
                "FormatEPUB",
                "FormatHTML"
            ]
        },
        "models.ClippingStatus": {
            "type": "string",
            "enum": [
                "completed",
                "pending",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusCompleted",
                "StatusPending",
                "StatusFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ReadFriendly API",
	Description:      "Makes webpages friendly to read",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
